⚙️ Chore:
  - '.github/*'
  - '.tools/*'
  - './*'

🃏 Demos:
  - ./apps/demos/*
  - ./apps/demos/**/*

'🛠️ CDK':
  - libs/cdk/*
  - libs/cdk/**/*

'{ } State':
  - libs/state/*
  - libs/state/**/*

'</> Template':
  - libs/template/*
  - libs/template/**/*

'🚀 ISR':
  - libs/isr/*
  - libs/isr/**/*

'📐 ESLint plugin':
  - libs/eslint-plugin/*
  - libs/eslint-plugin/**/*

📖 Docs API:
  - libs/**/docs/**/*

📚 Docs Web:
  - apps/docs/*
  - apps/docs/**/*

🔬 Experimental:
  - libs/**/experimental/*
  - libs/**/experimental/**/*

🛂 Test:
  - libs/**/spec/*
  - libs/**/spec/**/*
  - libs/**/perf/*
  - libs/**/perf/**/*
